// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gezrcuwrspltcjdeswcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlenJjdXdyc3BsdGNqZGVzd2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzgxNjEsImV4cCI6MjA2NDUxNDE2MX0.KL2FIooh9U-SYbdPKdIabz53UkQlF9Cg9lFFWvu2ecE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);